gui:
  scrollHeight: 2
  theme:
    activeBorderColor:
    - green
    - bold
    inactiveBorderColor:
    - white
    optionsTextColor:
    - blue
  returnImmediately: false
  wrapMainPanel: false
reporting: false
commandTemplates:
  restartService: '{{ .DockerCompose }} restart {{ .Service.Name }}'
  dockerCompose: docker-compose
  stopService: '{{ .DockerCompose }} stop {{ .Service.Name }}'
  serviceLogs: '{{ .DockerCompose }} logs --since=60m --follow {{ .Service.Name }}'
  viewServiceLogs: '{{ .DockerCompose }} logs --follow {{ .Service.Name }}'
  rebuildService: '{{ .DockerCompose }} up -d --build {{ .Service.Name }}'
  recreateService: '{{ .DockerCompose }} up -d --force-recreate {{ .Service.Name }}'
  viewContainerLogs: docker logs --timestamps --follow --since=60m {{ .Container.ID}}
  containerLogs: docker logs --timestamps --follow --since=60m {{ .Container.ID }}
  allLogs: '{{ .DockerCompose }} logs --tail=300 --follow'
  viewAlLogs: '{{ .DockerCompose }} logs'
  dockerComposeConfig: '{{ .DockerCompose }} config'
  checkDockerComposeConfig: '{{ .DockerCompose }} config --quiet'
  serviceTop: '{{ .DockerCompose }} top {{ .Service.Name }}'
customCommands:
  containers:
  - name: bash
    attach: true
    command: docker exec -it {{ .Container.ID }} /bin/sh
    serviceNames: []
  - name: migrate
    attach: true
    command: docker exec -it {{ .Container.ID }} php /var/www/html/artisan migrate
    serviceNames: [php]
  - name: module:migrate
    attach: true
    command: docker exec -it {{ .Container.ID }} php /var/www/html/artisan module:migrate
    serviceNames: [php]
  - name: composer
    attach: false
    command: docker run --name=composer --rm -v /Users/sam/projects/udify/udify-api:/var/www/html --user=www-data --workdir="/var/www/html" portal-docker_composer:latest composer update --ignore-platform-reqs
    serviceNames: []
  - name: npm-install
    attach: true
    command: docker run --name=npm-install --rm -v /Users/sam/projects/udify/udify-api:/var/www/html --workdir="/var/www/html" node:13.7 npm install
    serviceNames: []
  - name: npm-run-dev
    attach: false
    command: docker run --name=npm-run-dev --rm -v /Users/sam/projects/udify/udify-api:/var/www/html --workdir="/var/www/html" node:13.7 npm run dev
    serviceNames: []

oS:
  openCommand: open {{filename}}
  openLinkCommand: open {{link}}
update:
  dockerRefreshInterval: 100ms
stats:
  graphs:
  - caption: CPU (%)
    statPath: DerivedStats.CPUPercentage
    color: blue
  - caption: Memory (%)
    statPath: DerivedStats.MemoryPercentage
    color: green